### ISSUE TITLE
something about continue_train

### ISSUE THREAD

**Issue by chenpengf0223** [chenyilun95/tf-cpn#50]
Hi, if I  want to finetune the 350epoch-snapshot.ckpt model on my own keypoints data, if I need to set the cfg variable "continue_train" to True?

**Comment by ttdd11** [comment]
@chenpengf0223 Did you ever fine tune the model with your own keypoints?

**Comment by chenpengf0223** [comment]
@ttdd11    yes.

**Comment by ttdd11** [comment]
@chenpengf0223  So you loaded the 350 and tuned it with more joints/different joints or just different data? What were your training parameters and how long did you run it? Was the end result pretty good? Just wondering if I should bother tuning or restart the training with my own data (since it takes so long).

**Comment by chenpengf0223** [comment]
@ttdd11   I tuned  the 350 ckpt with different joints. My training parameters are: lr = 1e-3,  lr_gamma = 0.5, lr_dec_epoch = 60, optimizer = 'adam', batch_size = 28, weight_decay = 1e-5. I finally use the model after 50 epochs.
I think the training depends on your data, if it is a different distribution with coco and has a large amount, you should train from scratch, otherwise, you can fine tune the model with it.
